// <auto-generated />
using EF_SQL_Server.DB_Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFSQLServer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230131171020_Inicial4")]
    partial class Inicial4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EF_SQL_Server.Models.Jutsu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NarutoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NarutoId");

                    b.ToTable("Jutsus");
                });

            modelBuilder.Entity("EF_SQL_Server.Models.Naruto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Clan")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("EF_SQL_Server.Models.Jutsu", b =>
                {
                    b.HasOne("EF_SQL_Server.Models.Naruto", "Naruto")
                        .WithMany("Jutsus")
                        .HasForeignKey("NarutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Naruto");
                });

            modelBuilder.Entity("EF_SQL_Server.Models.Naruto", b =>
                {
                    b.Navigation("Jutsus");
                });
#pragma warning restore 612, 618
        }
    }
}
